# fly.toml app configuration file generated for aged-bush-8548 on 2023-11-01T21:52:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aged-bush-8548"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
