# fly.toml app configuration file generated for proud-darkness-8341 on 2023-11-01T22:13:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proud-darkness-8341"
primary_region = "arn"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
